# Generated by Django 4.1.5 on 2023-02-18 23:40

import NewApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=NewApp.models.get_file_path),
        ),
    ]
