# Generated by Django 4.1.5 on 2023-02-18 23:41

import NewApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to=NewApp.models.banner_image_file)),
                ('category', models.CharField(choices=[], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[], max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=NewApp.models.get_file_path)),
                ('quantity', models.IntegerField()),
                ('small_description', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
            ],
        ),
    ]
