# Generated by Django 4.1.5 on 2023-02-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0005_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
