# Generated by Django 4.1.5 on 2023-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0008_alter_banner_image_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_image',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Non-Active', '')], default=False, max_length=150),
        ),
    ]
