# Generated by Django 4.1.5 on 2023-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0012_alter_banner_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_image',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('', 'Non-Active')], max_length=150),
        ),
    ]
