# Generated by Django 4.1.5 on 2023-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0014_alter_banner_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
