# Generated by Django 4.1.5 on 2023-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0015_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
